---
sidebar: sidebar 
permalink: task_vcp_remove.html 
summary: Upgraden Sie das aktuelle NetApp Element Plug-in für VMware vCenter Server. 
keywords: netapp, vcp, vcenter, plugin, element, upgrade 
---
= Entfernen Sie das vCenter Plug-in
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Bei vCenter Plug-in 4.0 bis 4.10, das in vSphere 6.7 oder früher eingesetzt wird, müssen Sie den folgenden Prozess durchführen, um alle dem Plug-in zugeordneten Dateien manuell aus vCenter Server zu entfernen. Bei vSphere 7.0 und höher ist es nicht erforderlich, Dateien zu entfernen, nachdem Sie das Plug-in registriert haben.

.Was Sie benötigen
* VCenter Plug-in 4.0 bis 4.10
* VSphere 6.7 oder früher
* Das ist schon link:task_vcp_unregister.html["Nicht registriert"] Das vorhandene Plug-in und verfügen über SSH, RDP oder andere geeignete Verbindungen zu vCSA oder vCenter Server.


.Schritte
. Melden Sie sich als Administrator bei dem Server an, auf dem vCenter Server ausgeführt wird, und öffnen Sie eine Eingabeaufforderung.
. Stoppen Sie vCenter Server Services:
+
** Windows:
+
*** (Für Flash-Clients) führen Sie den folgenden Befehl aus:
+
[listing]
----
C:\Program Files\VMware\vCenter Server\vmon>.\vmon-cli --stop vsphere-client
----
*** (Für HTML5-Clients) führen Sie folgende Befehle aus:
+
[listing]
----
C:\Program Files\VMware\vCenter Server\vmon>.\vmon-cli --stop vsphere-client
C:\Program Files\VMware\vCenter Server\vmon>.\vmon-cli --stop vsphere-ui
----


** VCenter Server Appliance (vCSA)
+
*** (Für Flash-Clients) führen Sie den folgenden Befehl aus:
+
[listing]
----
service-control --stop vsphere-client
----
*** (Für HTML5-Clients) führen Sie folgende Befehle aus:
+
[listing]
----
service-control --stop vsphere-client
service-control --stop vsphere-ui
----




. Entfernen Sie SolidFire-Ordner und -Dateien aus den folgenden Speicherorten:
+
** (Unter Windows) Verwenden Sie Windows Explorer und suchen Sie nach `SolidFire` In `C:\ProgramData\VMware` Und `C:\Program Files\VMware`.
+

NOTE: Der Ordner ProgramData ist ausgeblendet. Sie müssen den vollständigen Dateipfad eingeben, um auf den Ordner zuzugreifen.

** (Für vCSA) führen Sie den folgenden Befehl aus:
+
[listing]
----
find / -name "*solidfire*" -exec rm -rf {} \;
----


. Starten Sie vCenter Server Services:
+
** Windows:
+
*** (Für Flash-Clients) führen Sie den folgenden Befehl aus:
+
[listing]
----
C:\Program Files\VMware\vCenter Server\vmon>.\vmon-cli --start vsphere-client
----
*** (Für HTML5-Clients) führen Sie folgende Befehle aus:
+
[listing]
----
C:\Program Files\VMware\vCenter Server\vmon>.\vmon-cli --start vsphere-client
C:\Program Files\VMware\vCenter Server\vmon>.\vmon-cli --start vsphere-ui
----


** VCSA:
+
*** (Für Flash-Clients) führen Sie den folgenden Befehl aus:
+
[listing]
----
service-control --start vsphere-client
----
*** (Für HTML5-Clients) führen Sie folgende Befehle aus:
+
[listing]
----
service-control --start vsphere-client
service-control --start vsphere-ui
----








== Weitere Informationen

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI-Dokumentation"^]
* https://www.netapp.com/data-storage/solidfire/documentation["Seite „SolidFire und Element Ressourcen“"^]

