---
sidebar: sidebar 
permalink: task_vcp_upgrades.html 
summary: Upgraden Sie das aktuelle NetApp Element Plug-in für VMware vCenter Server. 
keywords: netapp, vcp, vcenter, plugin, element, upgrade 
---
= Aktualisieren Sie das Plug-in
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können ein Upgrade des NetApp Element Plug-ins für vCenter Server durchführen, indem Sie die für Ihre Installation beschriebenen Schritte ausführen. Das NetApp Element vCenter Plug-in 5.0 ist außerhalb von Element und NetApp HCI Versionen als Teil eines Management Services Bundles verfügbar.

[NOTE]
====
* Ab dem Element Plug-in für vCenter 5.0 werden nur VMware vSphere 8.0 und 7.0 unterstützt.
* Wenn Sie ein Upgrade vom Element Plug-in für vCenter 4.x auf 5.0 durchführen, gehen die bereits mit dem Plug-in konfigurierten Cluster verloren, da die Daten nicht von einer vCenter Instanz in ein Remote-Plug-in kopiert werden können. Sie müssen die Cluster dem Remote-Plug-in erneut hinzufügen. Dies ist eine einmalige Aktivität beim Upgrade von einem lokalen auf ein Remote-Plug-in.


====
Befolgen Sie zum Aktualisieren des Plug-ins die Anweisungen in der Upgrade-Dokumentation für Ihr Produkt:

* https://docs.netapp.com/us-en/hci/docs/task_vcp_upgrade_plugin.html["Führen Sie ein Upgrade Ihres NetApp HCI Systems durch"^]
* https://docs.netapp.com/us-en/element-software/upgrade/task_vcp_upgrade_plugin.html["Rüsten Sie Ihr SolidFire All-Flash-Storage-System auf"^]




== Weitere Informationen

* https://library.netapp.com/ecm/ecm_download_file/ECMLP2884992["VCenter Plug-in 5.0 – Versionshinweise"^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["Versionshinweise zu Hybrid Cloud Control and Management Services"^]
* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI-Dokumentation"^]
* http://mysupport.netapp.com/hci/resources["Ressourcen-Seite zu NetApp HCI"^]
* https://www.netapp.com/data-storage/solidfire/documentation["Seite „SolidFire und Element Ressourcen“"^]

