---
sidebar: sidebar 
permalink: vcp_task_create_manage_access_groups.html 
summary: Sie können Volume-Zugriffsgruppen mithilfe des Plug-ins erstellen und verwalten. 
keywords: netapp, storage, access groups, vcp, vcenter, element 
---
= Erstellung und Management von Volume-Zugriffsgruppen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A link:https://docs.netapp.com/us-en/hci/docs/concept_hci_volume_access_groups.html["Volume-Zugriffsgruppe"^] Ist eine Sammlung von Volumes, auf die Benutzer entweder über iSCSI-Initiatoren oder FC-Initiatoren zugreifen können.

Sie können Zugriffsgruppen erstellen, indem Sie iSCSI-Initiator-IQNs oder FC-WWPNs in einer Sammlung von Volumes zuordnen. Jeder IQN, den Sie einer Zugriffsgruppe hinzufügen, kann auf jedes Volume in der Gruppe zugreifen, ohne dass eine CHAP-Authentifizierung erforderlich ist. Jeder WWPN, den Sie einer Zugriffsgruppe hinzufügen, ermöglicht den FC-Netzwerkzugriff auf die Volumes in der Zugriffsgruppe.

.Optionen
*  an access group
*  an access group
*  volumes to an access group
*  volumes from an access group
*  an access group




== Erstellen Sie eine Zugriffsgruppe

Sie können Volume-Zugriffsgruppen mit einem oder mehreren Initiatoren erstellen. Das Zuordnen von Fibre Channel- (WWPN) oder iSCSI-(IQN)-Client-Initiatoren zu den Volumes in einer Volume-Zugriffsgruppe ermöglicht sichere Daten-I/O zwischen einem Netzwerk und einem Volume.

.Schritte
. Öffnen Sie in Ihrem vSphere Web Client die Registerkarte *Management*:
+
** Ab Element vCenter Plug-in 5.0 wählen Sie *NetApp Element Remote Plugin > Management > Management*.
** Wählen Sie für Element vCenter Plug-in 4.10 und früher die Option *NetApp Element-Verwaltung > Verwaltung* aus.


+

NOTE: Wenn zwei oder mehr Cluster hinzugefügt werden, stellen Sie sicher, dass der Cluster, den Sie für die Aufgabe verwenden möchten, in der Navigationsleiste ausgewählt ist.

. Wählen Sie die Unterregisterkarte *Zugriffsgruppen* aus.
. Wählen Sie *Zugriffsgruppe Erstellen*.
. Geben Sie einen Namen für die Zugriffsgruppe des Volumes ein.
+

TIP: Verwenden Sie beschreibende Best Practices für die Benennung. Dies ist besonders wichtig, wenn in Ihrer Umgebung mehrere Cluster oder vCenter Server verwendet werden.

. Wählen Sie aus der Dropdown-Liste *Select an Initiator* einen nicht zugewiesenen IQN oder WWPN aus, und klicken Sie auf *Initiator hinzufügen*.
+

NOTE: Initiatoren können nach dem Erstellen der Volume-Zugriffsgruppe hinzugefügt oder gelöscht werden.

. Klicken Sie auf *OK*, um die Zugriffsgruppe zu erstellen.




== Bearbeiten Sie eine Zugriffsgruppe

Sie können Volume Access Group Namen bearbeiten oder Initiatoren aus dem Plug-in-Erweiterungspunkt hinzufügen oder entfernen.

.Schritte
. Öffnen Sie in Ihrem vSphere Web Client die Registerkarte *Management*:
+
** Ab Element vCenter Plug-in 5.0 wählen Sie *NetApp Element Remote Plugin > Management > Management*.
** Wählen Sie für Element vCenter Plug-in 4.10 und früher die Option *NetApp Element-Verwaltung > Verwaltung* aus.


+

NOTE: Wenn zwei oder mehr Cluster hinzugefügt werden, stellen Sie sicher, dass der Cluster, den Sie für die Aufgabe verwenden möchten, in der Navigationsleiste ausgewählt ist.

. Wählen Sie die Unterregisterkarte *Zugriffsgruppen* aus.
. Aktivieren Sie das Kontrollkästchen für die Volume Access Group, die Sie bearbeiten möchten.
. Wählen Sie *Aktionen*.
. Wählen Sie im Menü Ergebnis die Option *Bearbeiten*.
. Ändern Sie bei Bedarf Folgendes:
+
.. Ändern Sie den Namen der Zugriffsgruppe.
.. Hinzufügen oder Entfernen von Initiatoren.
+

NOTE: Wenn Sie einen Initiator entfernen, klicken Sie auf das Papierkorb-Symbol, um ihn zu entfernen. Wenn Sie den Initiator entfernen, kann er nicht mehr auf die Volumes in dieser Volume-Zugriffsgruppe zugreifen. Der normale Account-Zugriff auf das Volume wird nicht unterbrochen.



. Wählen Sie *OK*.




== Fügen Sie einer Zugriffsgruppe Volumes hinzu

Sie können Volumes zu einer Volume-Zugriffsgruppe hinzufügen. Jedes Volume kann mehr als einer Volume-Zugriffsgruppe angehören. Sie sehen die Gruppen, zu denen jedes Volume gehört, aus der Ansicht „Aktive Volumes“.

.Was Sie und#8217;ll benötigen
* Mindestens ein Cluster muss hinzugefügt und ausgeführt werden.
* Mindestens eine Zugriffsgruppe ist vorhanden.
* Mindestens ein aktives Volume ist vorhanden.


.Schritte
. Öffnen Sie in Ihrem vSphere Web Client die Registerkarte *Management*:
+
** Ab Element vCenter Plug-in 5.0 wählen Sie *NetApp Element Remote Plugin > Management > Management*.
** Wählen Sie für Element vCenter Plug-in 4.10 und früher die Option *NetApp Element-Verwaltung > Verwaltung* aus.


+

NOTE: Wenn zwei oder mehr Cluster hinzugefügt werden, stellen Sie sicher, dass der Cluster, den Sie für die Aufgabe verwenden möchten, in der Navigationsleiste ausgewählt ist.

. Wählen Sie die Unterregisterkarte *Volumes* aus.
. Aktivieren Sie das Kontrollkästchen für jedes Volume, das einer Zugriffsgruppe hinzugefügt werden soll.
. Wählen Sie *Aktionen*.
. Wählen Sie *zur Zugriffsgruppe hinzufügen*.
. Bestätigen Sie die Details und wählen Sie eine Zugriffsgruppe für Volumes aus der Liste aus.
. Wählen Sie *OK*.




== Volumes aus einer Zugriffsgruppe entfernen

Sie können Volumes aus einer Zugriffsgruppe entfernen.

Wenn Sie ein Volume aus einer Zugriffsgruppe entfernen, hat die Gruppe keinen Zugriff mehr auf dieses Volume.


IMPORTANT: Durch das Entfernen eines Volumes aus einer Zugriffsgruppe kann der Hostzugriff auf das Volume unterbrochen werden.

. Öffnen Sie in Ihrem vSphere Web Client die Registerkarte *Management*:
+
** Ab Element vCenter Plug-in 5.0 wählen Sie *NetApp Element Remote Plugin > Management > Management*.
** Wählen Sie für Element vCenter Plug-in 4.10 und früher die Option *NetApp Element-Verwaltung > Verwaltung* aus.


+

NOTE: Wenn zwei oder mehr Cluster hinzugefügt werden, stellen Sie sicher, dass der Cluster, den Sie für die Aufgabe verwenden möchten, in der Navigationsleiste ausgewählt ist.

. Wählen Sie die Unterregisterkarte *Volumes* aus.
. Aktivieren Sie das Kontrollkästchen für jedes Volume, das Sie aus einer Zugriffsgruppe entfernen möchten.
. Wählen Sie *Aktionen*.
. Wählen Sie *aus Zugriffsgruppe entfernen*.
. Bestätigen Sie die Details, und wählen Sie die Zugriffsgruppe für das Volume aus, die Sie nicht mehr auf jedes ausgewählte Volume zugreifen möchten.
. Wählen Sie *OK*.




== Löschen Sie eine Zugriffsgruppe

Sie können Volume Access Groups mit dem Plug-in-Erweiterungspunkt löschen. Sie müssen Initiator-IDs löschen oder Volumes aus der Zugriffsgruppe des Volumes entfernen, bevor Sie die Gruppe löschen. Nachdem Sie die Zugriffsgruppe gelöscht haben, wird der Gruppenzugriff auf die Volumes abgebrochen.

.Schritte
. Öffnen Sie in Ihrem vSphere Web Client die Registerkarte *Management*:
+
** Ab Element vCenter Plug-in 5.0 wählen Sie *NetApp Element Remote Plugin > Management > Management*.
** Wählen Sie für Element vCenter Plug-in 4.10 und früher die Option *NetApp Element-Verwaltung > Verwaltung* aus.


+

NOTE: Wenn zwei oder mehr Cluster hinzugefügt werden, stellen Sie sicher, dass der Cluster, den Sie für die Aufgabe verwenden möchten, in der Navigationsleiste ausgewählt ist.

. Wählen Sie die Unterregisterkarte *Zugriffsgruppen* aus.
. Aktivieren Sie das Kontrollkästchen für die Zugriffsgruppe, die Sie löschen möchten.
. Wählen Sie *Aktionen*.
. Wählen Sie im Menü Ergebnis die Option *Löschen* aus.
. Bestätigen Sie die Aktion.




== Weitere Informationen

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI-Dokumentation"^]
* https://www.netapp.com/data-storage/solidfire/documentation["Seite „SolidFire und Element Ressourcen“"^]

